version: '3'

services:
  nginx:
    container_name: nginx
    #image: nginx:latest
    image: nginx:1.15-alpine
    # Вместо Dockerfile берем готовый nginx (:latest - последняя версия) с docker hub
    restart: unless-stopped
    networks:
      nginx_net:
    # Подключаемся к новой сети в этом контейнере
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/WWW:/var/www
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      # Порт 80 будет доступен как в контейнере, так и снаружи.
      - 443:443
      # Открываем порты для ssl соединения
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
      # Перезапустит nginx контейнер каждые 6 часов и подгрузит новые сертификаты, если есть
  
  certbot:
    # Новый контейнер, который запуститься вместе с nginx
    container_name: certbot
    image: certbot/certbot
    # Образ берется с docker hub
    restart: unless-stopped
    # Перезапустит контейнер в непредвиденных ситуациях
    networks:
      nginx_net:
      # Подключаем к той-же сети, что и остальные контейнеры
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  #  entrypoint:  "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # Проверяет каждые 12 часов, нужны ли новые сертификаты

      
networks:
# Блок для объявления внутренних docker сетей, которые запустятся с этим файлом
  nginx_net:
  # Название сети для этого контейнера
    name: nginx_net
    # Название сети для внешних контейнеров