version: "3"
services:
  mongo:
    image: mongo:4.4.4
    container_name: mongo-any-4.1
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myadmin
      - MONGO_INITDB_ROOT_PASSWORD=myadmin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-any-4.1:/data/db
    command: --wiredTigerCacheSizeGB 1.5
